#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHT
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QL_NhanSu")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKhoiPhongBan(KhoiPhongBan instance);
    partial void UpdateKhoiPhongBan(KhoiPhongBan instance);
    partial void DeleteKhoiPhongBan(KhoiPhongBan instance);
    partial void InsertPhongBan(PhongBan instance);
    partial void UpdatePhongBan(PhongBan instance);
    partial void DeletePhongBan(PhongBan instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::QLHT.Properties.Settings.Default.QL_NhanSuConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<KhoiPhongBan> KhoiPhongBans
		{
			get
			{
				return this.GetTable<KhoiPhongBan>();
			}
		}
		
		public System.Data.Linq.Table<PhongBan> PhongBans
		{
			get
			{
				return this.GetTable<PhongBan>();
			}
		}

        public System.Data.Linq.Table<ChungChi> ChungChis
        {
            get
            {
                return this.GetTable<ChungChi>();
            }
        }

        public System.Data.Linq.Table<BacLuong> BacLuongs
        {
            get
            {
                return this.GetTable<BacLuong>();
            }
        }

        public System.Data.Linq.Table<MucXang> MucXangs
        {
            get
            {
                return this.GetTable<MucXang>();
            }
        }

        public System.Data.Linq.Table<ChamCong2> ChamCong2s
        {
            get
            {
                return this.GetTable<ChamCong2>();
            }
        }
    }
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhoiPhongBan")]
	public partial class KhoiPhongBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKhoiPhongBan;
		
		private string _TenKhoiPhongBan;
		
		private EntitySet<PhongBan> _PhongBans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhoiPhongBanChanging(int value);
    partial void OnMaKhoiPhongBanChanged();
    partial void OnTenKhoiPhongBanChanging(string value);
    partial void OnTenKhoiPhongBanChanged();
    #endregion
		
		public KhoiPhongBan()
		{
			this._PhongBans = new EntitySet<PhongBan>(new Action<PhongBan>(this.attach_PhongBans), new Action<PhongBan>(this.detach_PhongBans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoiPhongBan", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaKhoiPhongBan
		{
			get
			{
				return this._MaKhoiPhongBan;
			}
			set
			{
				if ((this._MaKhoiPhongBan != value))
				{
					this.OnMaKhoiPhongBanChanging(value);
					this.SendPropertyChanging();
					this._MaKhoiPhongBan = value;
					this.SendPropertyChanged("MaKhoiPhongBan");
					this.OnMaKhoiPhongBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhoiPhongBan", DbType="NVarChar(255)")]
		public string TenKhoiPhongBan
		{
			get
			{
				return this._TenKhoiPhongBan;
			}
			set
			{
				if ((this._TenKhoiPhongBan != value))
				{
					this.OnTenKhoiPhongBanChanging(value);
					this.SendPropertyChanging();
					this._TenKhoiPhongBan = value;
					this.SendPropertyChanged("TenKhoiPhongBan");
					this.OnTenKhoiPhongBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhoiPhongBan_PhongBan", Storage="_PhongBans", ThisKey="MaKhoiPhongBan", OtherKey="MaKhoiPhongBan")]
		public EntitySet<PhongBan> PhongBans
		{
			get
			{
				return this._PhongBans;
			}
			set
			{
				this._PhongBans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhongBans(PhongBan entity)
		{
			this.SendPropertyChanging();
			entity.KhoiPhongBan = this;
		}
		
		private void detach_PhongBans(PhongBan entity)
		{
			this.SendPropertyChanging();
			entity.KhoiPhongBan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhongBan")]
	public partial class PhongBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaPhongBan;
		
		private int _Stt;
		
		private string _TenPhongBan;
		
		private System.Nullable<int> _DoTuoiVeHuuNam;
		
		private System.Nullable<int> _DoTuoiVeHuuNu;
		
		private System.Nullable<int> _SoLaoDong;
		
		private System.Nullable<int> _MaKhoiPhongBan;
		
		private EntityRef<KhoiPhongBan> _KhoiPhongBan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhongBanChanging(int value);
    partial void OnMaPhongBanChanged();
    partial void OnSttChanging(int value);
    partial void OnSttChanged();
    partial void OnTenPhongBanChanging(string value);
    partial void OnTenPhongBanChanged();
    partial void OnDoTuoiVeHuuNamChanging(System.Nullable<int> value);
    partial void OnDoTuoiVeHuuNamChanged();
    partial void OnDoTuoiVeHuuNuChanging(System.Nullable<int> value);
    partial void OnDoTuoiVeHuuNuChanged();
    partial void OnSoLaoDongChanging(System.Nullable<int> value);
    partial void OnSoLaoDongChanged();
    partial void OnMaKhoiPhongBanChanging(System.Nullable<int> value);
    partial void OnMaKhoiPhongBanChanged();
    #endregion
		
		public PhongBan()
		{
			this._KhoiPhongBan = default(EntityRef<KhoiPhongBan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhongBan", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaPhongBan
		{
			get
			{
				return this._MaPhongBan;
			}
			set
			{
				if ((this._MaPhongBan != value))
				{
					this.OnMaPhongBanChanging(value);
					this.SendPropertyChanging();
					this._MaPhongBan = value;
					this.SendPropertyChanged("MaPhongBan");
					this.OnMaPhongBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stt", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Stt
		{
			get
			{
				return this._Stt;
			}
			set
			{
				if ((this._Stt != value))
				{
					this.OnSttChanging(value);
					this.SendPropertyChanging();
					this._Stt = value;
					this.SendPropertyChanged("Stt");
					this.OnSttChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhongBan", DbType="NVarChar(255)")]
		public string TenPhongBan
		{
			get
			{
				return this._TenPhongBan;
			}
			set
			{
				if ((this._TenPhongBan != value))
				{
					this.OnTenPhongBanChanging(value);
					this.SendPropertyChanging();
					this._TenPhongBan = value;
					this.SendPropertyChanged("TenPhongBan");
					this.OnTenPhongBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoTuoiVeHuuNam", DbType="Int")]
		public System.Nullable<int> DoTuoiVeHuuNam
		{
			get
			{
				return this._DoTuoiVeHuuNam;
			}
			set
			{
				if ((this._DoTuoiVeHuuNam != value))
				{
					this.OnDoTuoiVeHuuNamChanging(value);
					this.SendPropertyChanging();
					this._DoTuoiVeHuuNam = value;
					this.SendPropertyChanged("DoTuoiVeHuuNam");
					this.OnDoTuoiVeHuuNamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoTuoiVeHuuNu", DbType="Int")]
		public System.Nullable<int> DoTuoiVeHuuNu
		{
			get
			{
				return this._DoTuoiVeHuuNu;
			}
			set
			{
				if ((this._DoTuoiVeHuuNu != value))
				{
					this.OnDoTuoiVeHuuNuChanging(value);
					this.SendPropertyChanging();
					this._DoTuoiVeHuuNu = value;
					this.SendPropertyChanged("DoTuoiVeHuuNu");
					this.OnDoTuoiVeHuuNuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLaoDong", DbType="Int")]
		public System.Nullable<int> SoLaoDong
		{
			get
			{
				return this._SoLaoDong;
			}
			set
			{
				if ((this._SoLaoDong != value))
				{
					this.OnSoLaoDongChanging(value);
					this.SendPropertyChanging();
					this._SoLaoDong = value;
					this.SendPropertyChanged("SoLaoDong");
					this.OnSoLaoDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoiPhongBan", DbType="Int")]
		public System.Nullable<int> MaKhoiPhongBan
		{
			get
			{
				return this._MaKhoiPhongBan;
			}
			set
			{
				if ((this._MaKhoiPhongBan != value))
				{
					if (this._KhoiPhongBan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhoiPhongBanChanging(value);
					this.SendPropertyChanging();
					this._MaKhoiPhongBan = value;
					this.SendPropertyChanged("MaKhoiPhongBan");
					this.OnMaKhoiPhongBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhoiPhongBan_PhongBan", Storage="_KhoiPhongBan", ThisKey="MaKhoiPhongBan", OtherKey="MaKhoiPhongBan", IsForeignKey=true)]
		public KhoiPhongBan KhoiPhongBan
		{
			get
			{
				return this._KhoiPhongBan.Entity;
			}
			set
			{
				KhoiPhongBan previousValue = this._KhoiPhongBan.Entity;
				if (((previousValue != value) 
							|| (this._KhoiPhongBan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhoiPhongBan.Entity = null;
						previousValue.PhongBans.Remove(this);
					}
					this._KhoiPhongBan.Entity = value;
					if ((value != null))
					{
						value.PhongBans.Add(this);
						this._MaKhoiPhongBan = value.MaKhoiPhongBan;
					}
					else
					{
						this._MaKhoiPhongBan = default(Nullable<int>);
					}
					this.SendPropertyChanged("KhoiPhongBan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.ChungChi")]
    public partial class ChungChi : INotifyPropertyChanging, INotifyPropertyChanged
    {
        private static readonly PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
        private int _MaChungChi;
        private string _TenChungChi;
        private System.Nullable<int> _ThoiHan;
        private string _GhiChu;

        public ChungChi()
        {
            OnCreated();
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_MaChungChi", DbType = "Int NOT NULL", IsPrimaryKey = true)]
        public int MaChungChi
        {
            get { return this._MaChungChi; }
            set
            {
                if ((this._MaChungChi != value))
                {
                    this.OnMaChungChiChanging(value);
                    this.SendPropertyChanging();
                    this._MaChungChi = value;
                    this.SendPropertyChanged("MaChungChi");
                    this.OnMaChungChiChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_TenChungChi", DbType = "NVarChar(255)")]
        public string TenChungChi
        {
            get { return this._TenChungChi; }
            set
            {
                if ((this._TenChungChi != value))
                {
                    this.OnTenChungChiChanging(value);
                    this.SendPropertyChanging();
                    this._TenChungChi = value;
                    this.SendPropertyChanged("TenChungChi");
                    this.OnTenChungChiChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ThoiHan", DbType = "Int")]
        public System.Nullable<int> ThoiHan
        {
            get { return this._ThoiHan; }
            set
            {
                if ((this._ThoiHan != value))
                {
                    this.OnThoiHanChanging(value);
                    this.SendPropertyChanging();
                    this._ThoiHan = value;
                    this.SendPropertyChanged("ThoiHan");
                    this.OnThoiHanChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_GhiChu", DbType = "NVarChar(255)")]
        public string GhiChu
        {
            get { return this._GhiChu; }
            set
            {
                if ((this._GhiChu != value))
                {
                    this.OnGhiChuChanging(value);
                    this.SendPropertyChanging();
                    this._GhiChu = value;
                    this.SendPropertyChanged("GhiChu");
                    this.OnGhiChuChanged();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;
        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        // Add partial methods if needed
        partial void OnCreated();
        partial void OnMaChungChiChanging(int value);
        partial void OnMaChungChiChanged();
        partial void OnTenChungChiChanging(string value);
        partial void OnTenChungChiChanged();
        partial void OnThoiHanChanging(System.Nullable<int> value);
        partial void OnThoiHanChanged();
        partial void OnGhiChuChanging(string value);
        partial void OnGhiChuChanged();
    }

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.BacLuong")]
    public partial class BacLuong : INotifyPropertyChanging, INotifyPropertyChanged
    {
        private static readonly PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
        private int _MaBacLuong;
        private string _TenBacLuong;
        private DateTime _Ngay;
        // Khai báo các biến cho các cột Bac1, Bac2, ..., Bac10
        private float _Bac1;
        private float _Bac2;
        private float _Bac3;
        private float _Bac4;
        private float _Bac5;
        private float _Bac6;
        private float _Bac7;
        private float _Bac8;
        private float _Bac9;
        private float _Bac10;
        // Tiếp tục cho đến Bac10

        public BacLuong()
        {
            OnCreated();
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_MaBacLuong", DbType = "Int NOT NULL", IsPrimaryKey = true)]
        public int MaBacLuong
        {
            get { return this._MaBacLuong; }
            set
            {
                if ((this._MaBacLuong != value))
                {
                    this.OnMaBacLuongChanging(value);
                    this.SendPropertyChanging();
                    this._MaBacLuong = value;
                    this.SendPropertyChanged("MaBacLuong");
                    this.OnMaBacLuongChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_TenBacLuong", DbType = "NVarChar(255)")]
        public string TenBacLuong
        {
            get { return this._TenBacLuong; }
            set
            {
                if ((this._TenBacLuong != value))
                {
                    this.OnTenBacLuongChanging(value);
                    this.SendPropertyChanging();
                    this._TenBacLuong = value;
                    this.SendPropertyChanged("TenBacLuong");
                    this.OnTenBacLuongChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Ngay", DbType = "DateTime")]
        public DateTime Ngay
        {
            get { return this._Ngay; }
            set
            {
                if ((this._Ngay != value))
                {
                    this.OnNgayChanging(value);
                    this.SendPropertyChanging();
                    this._Ngay = value;
                    this.SendPropertyChanged("Ngay");
                    this.OnNgayChanged();
                }
            }
        }

        // Thuộc tính cho Bac1, Bac2, ..., Bac10
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Bac1", DbType = "Float")]
        public float Bac1
        {
            get { return this._Bac1; }
            set
            {
                if ((this._Bac1 != value))
                {
                    this.OnBac1Changing(value);
                    this.SendPropertyChanging();
                    this._Bac1 = value;
                    this.SendPropertyChanged("Bac1");
                    this.OnBac1Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Bac2", DbType = "Float")]
        public float Bac2
        {
            get { return this._Bac2; }
            set
            {
                if ((this._Bac2 != value))
                {
                    this.OnBac2Changing(value);
                    this.SendPropertyChanging();
                    this._Bac2 = value;
                    this.SendPropertyChanged("Bac2");
                    this.OnBac2Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Bac3", DbType = "Float")]
        public float Bac3
        {
            get { return this._Bac3; }
            set
            {
                if ((this._Bac3 != value))
                {
                    this.OnBac3Changing(value);
                    this.SendPropertyChanging();
                    this._Bac3 = value;
                    this.SendPropertyChanged("Bac3");
                    this.OnBac3Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Bac4", DbType = "Float")]
        public float Bac4
        {
            get { return this._Bac4; }
            set
            {
                if ((this._Bac4 != value))
                {
                    this.OnBac4Changing(value);
                    this.SendPropertyChanging();
                    this._Bac4 = value;
                    this.SendPropertyChanged("Bac4");
                    this.OnBac4Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Bac5", DbType = "Float")]
        public float Bac5
        {
            get { return this._Bac5; }
            set
            {
                if ((this._Bac5 != value))
                {
                    this.OnBac5Changing(value);
                    this.SendPropertyChanging();
                    this._Bac5 = value;
                    this.SendPropertyChanged("Bac5");
                    this.OnBac1Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Bac6", DbType = "Float")]
        public float Bac6
        {
            get { return this._Bac6; }
            set
            {
                if ((this._Bac6 != value))
                {
                    this.OnBac6Changing(value);
                    this.SendPropertyChanging();
                    this._Bac6 = value;
                    this.SendPropertyChanged("Bac6");
                    this.OnBac6Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Bac7", DbType = "Float")]
        public float Bac7
        {
            get { return this._Bac7; }
            set
            {
                if ((this._Bac7 != value))
                {
                    this.OnBac7Changing(value);
                    this.SendPropertyChanging();
                    this._Bac7 = value;
                    this.SendPropertyChanged("Bac7");
                    this.OnBac7Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Bac8", DbType = "Float")]
        public float Bac8
        {
            get { return this._Bac8; }
            set
            {
                if ((this._Bac8 != value))
                {
                    this.OnBac1Changing(value);
                    this.SendPropertyChanging();
                    this._Bac8 = value;
                    this.SendPropertyChanged("Bac8");
                    this.OnBac8Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Bac9", DbType = "Float")]
        public float Bac9
        {
            get { return this._Bac9; }
            set
            {
                if ((this._Bac9 != value))
                {
                    this.OnBac9Changing(value);
                    this.SendPropertyChanging();
                    this._Bac9 = value;
                    this.SendPropertyChanged("Bac9");
                    this.OnBac9Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Bac10", DbType = "Float")]
        public float Bac10
        {
            get { return this._Bac10; }
            set
            {
                if ((this._Bac10 != value))
                {
                    this.OnBac1Changing(value);
                    this.SendPropertyChanging();
                    this._Bac10 = value;
                    this.SendPropertyChanged("Bac10");
                    this.OnBac10Changed();
                }
            }
        }

        // Tiếp tục với Bac2, ..., Bac10

        public event PropertyChangingEventHandler PropertyChanging;
        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        // Các phương thức và sự kiện thay đổi cho mỗi thuộc tính
        partial void OnCreated();
        partial void OnMaBacLuongChanging(int value);
        partial void OnMaBacLuongChanged();
        partial void OnTenBacLuongChanging(string value);
        partial void OnTenBacLuongChanged();
        partial void OnNgayChanging(DateTime value);
        partial void OnNgayChanged();
        // Các phương thức và sự kiện cho Bac1, Bac2, ..., Bac10
        partial void OnBac1Changing(float value);
        partial void OnBac1Changed();

        partial void OnBac2Changing(float value);
        partial void OnBac2Changed();

        partial void OnBac3Changing(float value);
        partial void OnBac3Changed();

        partial void OnBac4Changing(float value);
        partial void OnBac4Changed();

        partial void OnBac5Changing(float value);
        partial void OnBac5Changed();

        partial void OnBac6Changing(float value);
        partial void OnBac6Changed();

        partial void OnBac7Changing(float value);
        partial void OnBac7Changed();

        partial void OnBac8Changing(float value);
        partial void OnBac8Changed();

        partial void OnBac9Changing(float value);
        partial void OnBac9Changed();

        partial void OnBac10Changing(float value);
        partial void OnBac10Changed();
        // Tiếp tục cho đến Bac10
    }

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.MucXang")]
    public partial class MucXang : INotifyPropertyChanging, INotifyPropertyChanged
    {
        private static readonly PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
        private int _ID;
        private DateTime _NgayApDung;
        private int _Muc1;
        private int _Muc2;
        private int _Muc3;
        private int _Muc4;

        public MucXang()
        {
            OnCreated();
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ID", DbType = "Int NOT NULL", IsPrimaryKey = true)]
        public int ID
        {
            get { return this._ID; }
            set
            {
                if ((this._ID != value))
                {
                    this.OnIDChanging(value);
                    this.SendPropertyChanging();
                    this._ID = value;
                    this.SendPropertyChanged("ID");
                    this.OnIDChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_NgayApDung", DbType = "DateTime")]
        public DateTime NgayApDung
        {
            get { return this._NgayApDung; }
            set
            {
                if ((this._NgayApDung != value))
                {
                    this.OnNgayApDungChanging(value);
                    this.SendPropertyChanging();
                    this._NgayApDung = value;
                    this.SendPropertyChanged("NgayApDung");
                    this.OnNgayApDungChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Muc1", DbType = "Int")]
        public int Muc1
        {
            get { return this._Muc1; }
            set
            {
                if ((this._Muc1 != value))
                {
                    this.OnMuc1Changing(value);
                    this.SendPropertyChanging();
                    this._Muc1 = value;
                    this.SendPropertyChanged("Muc1");
                    this.OnMuc1Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Muc2", DbType = "Int")]
        public int Muc2
        {
            get { return this._Muc2; }
            set
            {
                if ((this._Muc2 != value))
                {
                    this.OnMuc2Changing(value);
                    this.SendPropertyChanging();
                    this._Muc2 = value;
                    this.SendPropertyChanged("Muc2");
                    this.OnMuc2Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Muc3", DbType = "Int")]
        public int Muc3
        {
            get { return this._Muc3; }
            set
            {
                if ((this._Muc3 != value))
                {
                    this.OnMuc3Changing(value);
                    this.SendPropertyChanging();
                    this._Muc3 = value;
                    this.SendPropertyChanged("Muc3");
                    this.OnMuc3Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Muc4", DbType = "Int")]
        public int Muc4
        {
            get { return this._Muc4; }
            set
            {
                if ((this._Muc4 != value))
                {
                    this.OnMuc4Changing(value);
                    this.SendPropertyChanging();
                    this._Muc4 = value;
                    this.SendPropertyChanged("Muc4");
                    this.OnMuc4Changed();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;
        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        // Các phương thức và sự kiện thay đổi cho mỗi thuộc tính
        partial void OnCreated();
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        partial void OnNgayApDungChanging(DateTime value);
        partial void OnNgayApDungChanged();
        partial void OnMuc1Changing(int value);
        partial void OnMuc1Changed();
        partial void OnMuc2Changing(int value);
        partial void OnMuc2Changed();
        partial void OnMuc3Changing(int value);
        partial void OnMuc3Changed();
        partial void OnMuc4Changing(int value);
        partial void OnMuc4Changed();
    }

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.ChamCong2")]
    public partial class ChamCong2 : INotifyPropertyChanging, INotifyPropertyChanged
    {
        private static readonly PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
        private int _SoThuTu;
        private int _MaNhanVien;
        private string _TenNhanVien;
        private int _SoGioTangCa;
        private decimal _LuongCoBan;
        private decimal _TroCapDiLai;
        private decimal _TroCapNhaO;
        private decimal _TienHieuSuat;
        private decimal _BaoHiemXaHoi;
        private decimal _BaoHiemYTe;
        private decimal _BaoHiemTuNguyen;
        private decimal _PhiCongDoan;
        private decimal _ThucLinh;

        public ChamCong2()
        {
            OnCreated();
        }

        // Event declaration and property-changing notification
        public event PropertyChangingEventHandler PropertyChanging;
        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        // Column mappings and property definitions
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_SoThuTu", DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        public int SoThuTu
        {
            get { return this._SoThuTu; }
            set
            {
                if ((this._SoThuTu != value))
                {
                    this.OnSoThuTuChanging(value);
                    this.SendPropertyChanging();
                    this._SoThuTu = value;
                    this.SendPropertyChanged("SoThuTu");
                    this.OnSoThuTuChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_MaNhanVien", DbType = "Int NOT NULL")]
        public int MaNhanVien
        {
            get { return this._MaNhanVien; }
            set
            {
                if ((this._MaNhanVien != value))
                {
                    this.OnMaNhanVienChanging(value);
                    this.SendPropertyChanging();
                    this._MaNhanVien = value;
                    this.SendPropertyChanged("MaNhanVien");
                    this.OnMaNhanVienChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_TenNhanVien", DbType = "NVarChar(255)")]
        public string TenNhanVien
        {
            get { return this._TenNhanVien; }
            set
            {
                if ((this._TenNhanVien != value))
                {
                    this.OnTenNhanVienChanging(value);
                    this.SendPropertyChanging();
                    this._TenNhanVien = value;
                    this.SendPropertyChanged("TenNhanVien");
                    this.OnTenNhanVienChanged();
                }
            }
        }
        partial void OnTenNhanVienChanging(string value);
        partial void OnTenNhanVienChanged();

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_SoGioTangCa", DbType = "Int NOT NULL")]
        public int SoGioTangCa
        {
            get { return this._SoGioTangCa; }
            set
            {
                if ((this._SoGioTangCa != value))
                {
                    this.OnSoGioTangCaChanging(value);
                    this.SendPropertyChanging();
                    this._SoGioTangCa = value;
                    this.SendPropertyChanged("SoGioTangCa");
                    this.OnSoGioTangCaChanged();
                }
            }
        }
        partial void OnSoGioTangCaChanging(int value);
        partial void OnSoGioTangCaChanged();
        // Define other properties similarly...
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_LuongCoBan", DbType = "Decimal(18,2) NOT NULL")]
        public decimal LuongCoBan
        {
            get { return this._LuongCoBan; }
            set
            {
                if ((this._LuongCoBan != value))
                {
                    this.OnLuongCoBanChanging(value);
                    this.SendPropertyChanging();
                    this._LuongCoBan = value;
                    this.SendPropertyChanged("LuongCoBan");
                    this.OnLuongCoBanChanged();
                }
            }
        }

        // Các phương thức và sự kiện thay đổi cho LuongCoBan
        partial void OnLuongCoBanChanging(decimal value);
        partial void OnLuongCoBanChanged();

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_TroCapDiLai", DbType = "Decimal(18,2) NOT NULL")]
        public decimal TroCapDiLai
        {
            get { return this._TroCapDiLai; }
            set
            {
                if ((this._TroCapDiLai != value))
                {
                    this.OnTroCapDiLaiChanging(value);
                    this.SendPropertyChanging();
                    this._TroCapDiLai = value;
                    this.SendPropertyChanged("TroCapDiLai");
                    this.OnTroCapDiLaiChanged();
                }
            }
        }

        // Các phương thức và sự kiện thay đổi cho LuongCoBan
        partial void OnTroCapDiLaiChanging(decimal value);
        partial void OnTroCapDiLaiChanged();

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_TroCapNhaO", DbType = "Decimal(18,2) NOT NULL")]
        public decimal TroCapNhaO
        {
            get { return this._TroCapNhaO; }
            set
            {
                if ((this._TroCapNhaO != value))
                {
                    this.OnTroCapNhaOChanging(value);
                    this.SendPropertyChanging();
                    this._TroCapNhaO = value;
                    this.SendPropertyChanged("TroCapNhaO");
                    this.OnTroCapNhaOChanged();
                }
            }
        }

        // Các phương thức và sự kiện thay đổi cho LuongCoBan
        partial void OnTroCapNhaOChanging(decimal value);
        partial void OnTroCapNhaOChanged();

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_TienHieuSuat", DbType = "Decimal(18,2) NOT NULL")]
        public decimal TienHieuSuat
        {
            get { return this._TienHieuSuat; }
            set
            {
                if ((this._TienHieuSuat != value))
                {
                    this.OnTienHieuSuatChanging(value);
                    this.SendPropertyChanging();
                    this._TienHieuSuat = value;
                    this.SendPropertyChanged("TienHieuSuat");
                    this.OnTienHieuSuatChanged();
                }
            }
        }

        // Các phương thức và sự kiện thay đổi cho LuongCoBan
        partial void OnTienHieuSuatChanging(decimal value);
        partial void OnTienHieuSuatChanged();

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_BaoHiemXaHoi", DbType = "Decimal(18,2) NOT NULL")]
        public decimal BaoHiemXaHoi
        {
            get { return this._BaoHiemXaHoi; }
            set
            {
                if ((this._BaoHiemXaHoi != value))
                {
                    this.OnBaoHiemXaHoiChanging(value);
                    this.SendPropertyChanging();
                    this._BaoHiemXaHoi = value;
                    this.SendPropertyChanged("BaoHiemXaHoi");
                    this.OnBaoHiemXaHoiChanged();
                }
            }
        }

        partial void OnBaoHiemXaHoiChanging(decimal value);
        partial void OnBaoHiemXaHoiChanged();

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_BaoHiemYTe", DbType = "Decimal(18,2) NOT NULL")]
        public decimal BaoHiemYTe
        {
            get { return this._BaoHiemYTe; }
            set
            {
                if ((this._BaoHiemYTe != value))
                {
                    this.OnBaoHiemYTeChanging(value);
                    this.SendPropertyChanging();
                    this._BaoHiemYTe = value;
                    this.SendPropertyChanged("BaoHiemYTe");
                    this.OnBaoHiemYTeChanged();
                }
            }
        }

        // Các phương thức và sự kiện thay đổi cho LuongCoBan
        partial void OnBaoHiemYTeChanging(decimal value);
        partial void OnBaoHiemYTeChanged();

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_BaoHiemTuNguyen", DbType = "Decimal(18,2) NOT NULL")]
        public decimal BaoHiemTuNguyen
        {
            get { return this._BaoHiemTuNguyen; }
            set
            {
                if ((this._BaoHiemTuNguyen != value))
                {
                    this.OnBaoHiemTuNguyenChanging(value);
                    this.SendPropertyChanging();
                    this._BaoHiemTuNguyen = value;
                    this.SendPropertyChanged("BaoHiemTuNguyen");
                    this.OnBaoHiemTuNguyenChanged();
                }
            }
        }

        // Các phương thức và sự kiện thay đổi cho LuongCoBan
        partial void OnBaoHiemTuNguyenChanging(decimal value);
        partial void OnBaoHiemTuNguyenChanged();

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_PhiCongDoan", DbType = "Decimal(18,2) NOT NULL")]
        public decimal PhiCongDoan
        {
            get { return this._PhiCongDoan; }
            set
            {
                if ((this._PhiCongDoan != value))
                {
                    this.OnPhiCongDoanChanging(value);
                    this.SendPropertyChanging();
                    this._PhiCongDoan = value;
                    this.SendPropertyChanged("PhiCongDoan");
                    this.OnPhiCongDoanChanged();
                }
            }
        }

        // Các phương thức và sự kiện thay đổi cho LuongCoBan
        partial void OnPhiCongDoanChanging(decimal value);
        partial void OnPhiCongDoanChanged();

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ThucLinh", DbType = "Decimal(18,2) NOT NULL")]
        public decimal ThucLinh
        {
            get { return this._ThucLinh; }
            set
            {
                if ((this._ThucLinh != value))
                {
                    this.OnThucLinhChanging(value);
                    this.SendPropertyChanging();
                    this._ThucLinh = value;
                    this.SendPropertyChanged("ThucLinh");
                    this.OnThucLinhChanged();
                }
            }
        }

        // Các phương thức và sự kiện thay đổi cho LuongCoBan
        partial void OnThucLinhChanging(decimal value);
        partial void OnThucLinhChanged();

        // Partial methods for change tracking
        partial void OnCreated();
        partial void OnSoThuTuChanging(int value);
        partial void OnSoThuTuChanged();
        partial void OnMaNhanVienChanging(int value);
        partial void OnMaNhanVienChanged();
        // Define other partial methods for each property...
    }



}
#pragma warning restore 1591
